#!/bin/sh

# JAVA 
export JAVA_HOME=$SNAP/usr/lib/jvm/java-1.11.0-openjdk-$SNAP_ARCH
export PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH

# VARS
LAST_PATH=`pwd -P`
TARGET_FILE=$0
TARGET_FILE=`basename $TARGET_FILE`
PHYS_DIR=`pwd -P`
BASE_PATH=$PHYS_DIR

# Execute
cd $SNAP/bin/MegaLogViewer/
java -Xms512m -Xmx2048m -jar MegaLogViewer.jar $1
RESULT=$?

if [ -d "$LAST_PATH" ]; then
	cd "$LAST_PATH"
fi

exit $RESULT
