name: megalogviewer
version: 4.4.43
summary: MegaLogViewer MegaSquirt Edition (UNOFFICIAL)
description: |
  MegaLogViewer MegaSquirt Edition	
  
  After installing, run the following commands:
  
  sudo snap connect megalogviewer:removable-media
  
  This is NOT an officially supported snap from EFI Analytics. 

base: core20
grade: stable
confinement: strict
compression: lzo

assumes: 
  - command-chain
  
architectures:
  - build-on: amd64

apps:
  megalogviewer: 
    extensions: 
      - gnome-3-38
    command: launch
    command-chain: 
      - bin/homeishome-launch    
    plugs:
      - home
      - removable-media
      - browser-support
      - x11
      - desktop
      - desktop-legacy
      - network
    environment: 
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      JRE_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64/jre  
      
parts:
  tool:    
    plugin: nil
    override-build: | 
      mkdir -p BUILD
      cd BUILD/
      wget -O megalogviewer.tar.gz http://www.efianalytics.com/MegaLogViewer/download/MegaLogViewer_v4.4.43.tar.gz
      tar -xzvf megalogviewer.tar.gz
      rm megalogviewer.tar.gz
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp -r * $SNAPCRAFT_PART_INSTALL/bin/

    build-packages:
      - wget
      - tar
      
    stage-packages:
      - openjdk-11-jdk
      - openjdk-11-jre
      - librxtx-java
      - fontconfig
      - fontconfig-config
      - libfontconfig1
      - x11-xserver-utils
      - libgtk-3-dev   
      - ca-certificates-java
      - ca-certificates               

    stage:
    - -usr/lib/jvm/java-11-openjdk-*/lib/security/cacerts
    - -usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs 

  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch         
            
  launcher:
    plugin: dump
    source: scripts
    
   
  cleanup:
    after:
      - tool
      - launcher
    plugin: nil
    build-snaps: 
      - core20
      - gnome-3-38-2004
    
